### ISSUE TITLE
Data set loading issues

### ISSUE THREAD

**Issue by CodingNovice7** [AutodeskAILab/JoinABLe#2]
Hi, thanks for the open source code, it's a great job. I am now trying to reproduce your code and when I load the training dataset, the system's 16 GB of runtime memory are filled up causing the computer to crash and report process finished with exit code 137 (interupted by signal 9: SIGKILL). Now I don't know what to do.

**Comment by karldd** [comment]
Hi @lylwy 
Thanks. Yes it sounds like your memory is less than what we have been using. I think the options are:

1. Install more memory
2. Use the `--limit` flag, e.g. `python train.py --dataset path/to/dataset --exp_name my_experiment --limit 1000`, to limit the size of the dataset you load and train on.
3. Implement a data loader that doesn't hold everything in memory, but loads the data incrementally. See: https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html#creating-larger-datasets

Hope that helps!

**Comment by CodingNovice7** [comment]
> 

Thank you very much for your prompt reply, I'll try 2,3.

**Comment by karldd** [comment]
Sounds good. I'll close this issue, but feel free to reopen it later if you need to 👍
