### ISSUE TITLE
Using joinable with other datasets and other 3d formats

### ISSUE THREAD

**Issue by ttsesm** [AutodeskAILab/JoinABLe#6]
Hi @karldd,

thanks for this open source work and code, it seems quite a promissing job. I am now trying to reproduce your code and I would be interested to check whether I could adapt it for different datasets like the [Breaking bad](https://breaking-bad-dataset.github.io/) dataset. As I understand the 3d models need to be represented in a B-Rep format. So I have a couple of questions:

1. Thus, is there a way that I can obtain the B-Rep representation from .obj files and use them to train the model on a new dataset or even infer the pretrained models to the new dataset?
2. Can you elaborate a bit more on the weak supervision part, I am not sure I understood what in practice you mean with that?
3. How different would be to adapt the same principle for point clouds?

Thanks.

**Comment by karldd** [comment]
1. There isn't a robust and automatic way to do this. Its still an open research problem. You can look at commercial solutions like [this](https://knowledge.autodesk.com/support/fusion-360/learn-explore/caas/sfdcarticles/sfdcarticles/How-to-Convert-a-Mesh-to-a-BRep-in-Fusion-360.html).
2. This means that only some of the joints have labels, i.e. all possible realistic ways to label them are not provided. We train on just a subset of all possible labels.
3. I would take at the point cloud papers we reference in our paper.

**Comment by ttsesm** [comment]
Thanks for the reply!!!

> 1. There isn't a robust and automatic way to do this. Its still an open research problem. You can look at commercial solutions like [this](https://knowledge.autodesk.com/support/fusion-360/learn-explore/caas/sfdcarticles/sfdcarticles/How-to-Convert-a-Mesh-to-a-BRep-in-Fusion-360.html).
> 
I see, well this might be an issue. If it is not that easy to port from one format to the other this might be quite time consuming.

>     2. This means that only some of the joints have labels, i.e. all possible realistic ways to label them are not provided. We train on just a subset of all possible labels.
> 
Ok, however having only some joints labeled is enough? Also how do you choose which joints to label?

>     3. I would take at the point cloud papers we reference in our paper.
>
Sure, I will have a look on that ;-).

**Comment by karldd** [comment]
> Ok, however having only some joints labeled is enough? Also how do you choose which joints to label?

All data samples have at least one label. Some have more than 1. But none have an exhaustive set of labels.
