### ISSUE TITLE
`conda` environment using the yml file is taking forever

### ISSUE THREAD

**Issue by preethamam** [AutodeskAILab/JoinABLe#9]
Hello,

Creating the `conda` environment using the command `conda env create -f environment.yml` is taking forever and says `Solving environment`, even with the setting `conda config --set channel_priority flexible.` Is there a way to create a `conda` environment quickly? I also tried creating the `conda` environment using the default way and installing the packages individually. However, there are many conflicts due to `No matching distribution` errors. 

Below is the Terminal output:

```shell
conda env create -f environment.yml
Collecting package metadata (repodata.json): \ WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
done
Solving environment:
```

**Comment by karldd** [comment]
Have you tried mamba?
https://github.com/mamba-org/mamba

**Comment by preethamam** [comment]
@karldd, yes, `mamba` worked for all except `pip install pysdf`. I get the below error:

```shell
ERROR: Failed building wheel for pysdf
Running setup.py clean for pysdf
Failed to build pysdf
ERROR: Could not build wheels for pysdf, which is required to install pyproject.toml-based projects
```

**Comment by karldd** [comment]
I think you will need to ask the pysdf folks about that one. We only use it for the optimization part, so you may not need it if you ate interested in just the NN?

**Comment by preethamam** [comment]
@karldd, thanks! I will look into it. It is always good to have an optimized NN. I will check.

**Comment by preethamam** [comment]
@karldd, I solved the `pip install pysdf` issue by upgrading to the C++11 compiler using the command `sudo apt-get install build-essential -y`. I posted this just in case someone has the same issue.

**Comment by zikai1** [comment]
> Have you tried mamba? https://github.com/mamba-org/mamba

Yes, I also encountered the `conda` problem and I tried many solutions, but still failed. After using the `mamba`, the problem solved. Thank you!
